apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-3.6
spec:
  selector:
    matchLabels:
      app: python-3.6
  replicas: 3
  template:
    metadata:
      labels:
        app: python-3.6
    spec:
      containers:
      - name: python-3.6
        image: python3.6
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi" #128 MB
            cpu: "100m" #100 millicpu (.1 cpu or 10% of the cpu)